project_id = "rjhvqctjtgfpxzhnrozt"
[functions.create-portal-request]
enabled = true
verify_jwt = true
import_map = "./functions/create-portal-request/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-portal-request/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-portal-request/*.html" ]

[functions.calendar-feed]
enabled = true
verify_jwt = true
import_map = "./functions/calendar-feed/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calendar-feed/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calendar-feed/*.html" ]

[functions.sync-inbox]
enabled = true
verify_jwt = true
entrypoint = "./functions/sync-inbox/index.ts"

[functions.fetch-mail-body]
enabled = true
verify_jwt = true
entrypoint = "./functions/fetch-mail-body/index.ts"

[functions.send-customer-mail]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-customer-mail/index.ts"
